### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by titoudoc** [nicoduj/homebridge-gogogate2#10]
Hi, thank for this plugin. 
Could you add the temperature from the wireless sensor ?
Thanks.

**Comment by nicoduj** [comment]
Hi, definitely I can do this as well as battery status of garage door sensor I think. Will try asap

**Comment by titoudoc** [comment]
Thanks, would be great !

**Comment by nicoduj** [comment]
Hi, you can give a try to latest version !

**Comment by titoudoc** [comment]
Will try now ! Thank you so much !

**Comment by titoudoc** [comment]
Seems to work very very well ! A big thank you !

**Comment by designzguy** [comment]
This latest update has caused my homebridge setup to crash everytime I try to run it:

Error from log is below:

C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:749
          callback(undefined, false);
          ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:12:13
    at Gogogate2Platform.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:749:11)
    at emitThree (events.js:141:20)
    at Characteristic.ObstructionDetected.emit (events.js:217:7)
    at Characteristic.ObstructionDetected.Characteristic.getValue (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Characteristic.js:164:10)
    at Bridge.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:762:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:726:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:926:10)
    at HAPServer.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:209:39)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\bin>

**Comment by nicoduj** [comment]
Hi, @designzguy could you share your config ? Do you have multiple doors ?

**Comment by designzguy** [comment]
Yes, I have 2 doors and each door has it's own sensor. 
The plugin is probably trying to request the "Temperature" and "Battery" status for both doors at the same time and doesn't recognize that there are 2 separate doors/sensors.

**Comment by nicoduj** [comment]
Ok, that must be related. I only have one door right now so I must have made something wrong . I can’t test anymore this evening but tried something, if you can update manualy to give it a try . Also It might be possible that you have to empty your homebridge cache accessory since I moved from services on one accessory to multiple accessories
