### ISSUE TITLE
Latest update makes homebridge crash with multiple doors

### ISSUE THREAD

**Issue by nicoduj** [nicoduj/homebridge-gogogate2#11]
This latest update has caused my homebridge setup to crash everytime I try to run it:

Error from log is below:

C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:749
          callback(undefined, false);
          ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\util\once.js:12:13
    at Gogogate2Platform.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:749:11)
    at emitThree (events.js:141:20)
    at Characteristic.ObstructionDetected.emit (events.js:217:7)
    at Characteristic.ObstructionDetected.Characteristic.getValue (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Characteristic.js:164:10)
    at Bridge.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:762:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\Accessory.js:726:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:926:10)
    at HAPServer.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\lib\HAPServer.js:209:39)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge\bin>

_Originally posted by @designzguy in https://github.com/nicoduj/homebridge-gogogate2/issues/10#issuecomment-457858615_

**Comment by designzguy** [comment]
Ok so I installed the updated index.js file that you posted and I can now run homebridge without it crashing. 
Both garage doors show up and 1 temperature shows up. The temperature that shows up is for the single garage door. I have posted some photos for you to see. Also the battery status is showing up correctly for both doors in the settings for each door. 
https://1drv.ms/f/s!Amw8f9dO3fDt3DGbaVDrCQ5mPytc

**Comment by nicoduj** [comment]
Thank you ! Concerning the temp sensor, yes, I will fix that in #12, but great if it doesn't crash anymore. I'll try to publish an update today. Thanks for feedback and testing !

**Comment by nicoduj** [comment]
you can give a try to 0.0.9, hope I did everything ok (can't test in real conditions)

**Comment by designzguy** [comment]
I'll install the latest update and let you know the results in a little while. Thanks for all your efforts to get this working with all available options.

**Comment by designzguy** [comment]
I can confirm that the 0.1.0 version has fixed issue #11. Homebridge no longer crashes when running the plug-in with 2 separate garage doors.
