### ISSUE TITLE
get an error after loading gogogate into home bridge

### ISSUE THREAD

**Issue by d2too** [nicoduj/homebridge-gogogate2#44]
Here is the error I get when running home bridge command under CMD in admin mode on Windows 10
Also zipped up the config.json for you.

[config-gogo.json.zip](https://github.com/nicoduj/homebridge-gogogate2/files/4638237/config-gogo.json.zip)

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 59b36b9d-6409-460a-a078-f7cd532f6ef4
    at Bridge.Accessory._this.addBridgedAccessory (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:413:15)
    at Bridge.Accessory._this.addBridgedAccessories (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:447:12)
    at Server.handleRegisterPlatformAccessories (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:520:17)
    at HomebridgeAPI.emit (events.js:209:13)
    at HomebridgeAPI.registerPlatformAccessories (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:296:10)
    at Gogogate2Platform.loadDoors (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:229:22)
    at GogogateAPI.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:164:12)
    at GogogateAPI.emit (events.js:209:13)
    at Request.optionalCallback [as _callback] (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge-gogogate2\gogogateAPI.js:173:18)
    at Request.self.callback (C:\Users\User\AppData\Roaming\npm\node_modules\homebridge-gogogate2\node_modules\request\request.js:185:22)

**Comment by nicoduj** [comment]
configuration error (2 platforms, one empty, and thus device added 2 times)
