### ISSUE TITLE
plugin crashes homebridge

### ISSUE THREAD

**Issue by markrolfo** [nicoduj/homebridge-gogogate2#48]
see below error

 TypeError: $ is not a function
    at Request.optionalCallback [as _callback] (/usr/local/lib/node_modules/homebridge-gogogate2/gogogateAPI.js:161:15)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-gogogate2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-gogogate2/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-gogogate2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

below is the config

   {
            "name": "garage",
            "gogogateIP": "192.168.1.66",
            "username": "",
            "password": "",
            "refreshTimer": 0,
            "maxWaitTimeForOperation": 30,
            "refreshTimerDuringOperation": 10,
            "platform": "GogoGate2"
        }

**Comment by nicoduj** [comment]
￼hi, will take a look strange since mine is pretty stable. Did you make any change ?

I have edited your post to remove login / password by the way ...

**Comment by markrolfo** [comment]
Yeah no changes, running on OSX. 

Rest works a treat
