### ISSUE TITLE
plugin crashing, can't get to work

### ISSUE THREAD

**Issue by stevie-po** [nicoduj/homebridge-gogogate2#49]
First time installing, haven't succeeded in getting it to work yet? 

[6/3/2021, 4:41:58 PM] [WizSmarthome] [Socket] Socket Bound: UDP IPv4 listening on 192.168.1.2:38900
[6/3/2021, 4:41:58 PM] [WizSmarthome] [Discovery] Initiating discovery handlers
[6/3/2021, 4:41:58 PM] [WizSmarthome] [Discovery] Sending discovery UDP broadcast to 255.255.255.255:38899
Starting to advertise 'Homebridge CA82 2FEC' using bonjour-hap backend!
[6/3/2021, 4:41:58 PM] Homebridge v1.3.4 (Homebridge CA82) is running on port 51473.
[6/3/2021, 4:41:58 PM] [home] INFO - LOGIN - login ok
[6/3/2021, 4:41:58 PM] TypeError: $ is not a function
    at Request.optionalCallback [as _callback] (/homebridge/node_modules/homebridge-gogogate2/gogogateAPI.js:161:15)
    at Request.self.callback (/homebridge/node_modules/homebridge-gogogate2/node_modules/request/request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.<anonymous> (/homebridge/node_modules/homebridge-gogogate2/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:376:20)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-gogogate2/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[6/3/2021, 4:41:59 PM] Got SIGTERM, shutting down Homebridge...
[6/3/2021, 4:41:59 PM] [home] INFO - shutdown
[6/3/2021, 4:41:59 PM] [home] INFO - Logout - trying to logout
[6/3/2021, 4:41:59 PM] [WizSmarthome] [Socket] Shutting down socket
[6/3/2021, 4:42:03 PM] [Nest-cam] Found zone Zone 1 for Front
[6/3/2021, 4:42:03 PM] [Nest-cam] Found zone Zone 2 for Front
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Front Motion.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Front Sound.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Front Person.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Front Zone - Zone 1.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Front Zone - Zone 2.
[6/3/2021, 4:42:03 PM] [Nest-cam] Found zone Zone 1 for Back
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Back Motion.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Back Sound.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Back Person.
[6/3/2021, 4:42:03 PM] [Nest-cam] Creating motion sensor for Back Zone - Zone 1.
[6/3/2021, 4:42:04 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[6/3/2021, 4:42:09 PM] [HB Supervisor] Restarting Homebridge...
[6/3/2021, 4:42:09 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules -D
[6/3/2021, 4:42:09 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 11036
Initializing HAP-NodeJS v0.9.4...
[6/3/2021, 4:42:09 PM] Loaded config.json with 0 accessories and 5 platforms.
[6/3/2021, 4:42:09 PM] Loaded 2 cached accessories from cachedAccessories.
[6/3/2021, 4:42:09 PM] ---
[6/3/2021, 4:42:10 PM] Loaded plugin: homebridge-dummy@0.5.0
[6/3/2021, 4:42:10 PM] Registering accessory 'homebridge-dummy.DummySwitch'
[6/3/2021, 4:42:10 PM] ---
[6/3/2021, 4:42:10 PM] Loaded plugin: homebridge-gogogate2@1.1.4
[6/3/2021, 4:42:10 PM] Registering platform 'homebridge-gogogate2.GogoGate2'
[6/3/2021, 4:42:10 PM] ---
[6/3/2021, 4:42:10 PM] Loaded plugin: homebridge-nest-cam@7.3.0
[6/3/2021, 4:42:10 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[6/3/2021, 4:42:10 PM] ---
[6/3/2021, 4:42:11 PM] Disabled plugin: homebridge-sensibo-ac@2.1.8
[6/3/2021, 4:42:11 PM] ---
[6/3/2021, 4:42:11 PM] Loaded plugin: homebridge-wiz-lan@3.0.2
[6/3/2021, 4:42:11 PM] Registering platform 'homebridge-wiz-lan.WizSmarthome'
[6/3/2021, 4:42:11 PM] ---
[6/3/2021, 4:42:11 PM] Loaded plugin: homebridge-config-ui-x@4.41.1
[6/3/2021, 4:42:11 PM] Registering platform 'homebridge-config-ui-x.config'
[6/3/2021, 4:42:11 PM] ---
[6/3/2021, 4:42:11 PM] Loading 5 platforms...
[6/3/2021, 4:42:11 PM] [Config] Initializing config platform...
[6/3/2021, 4:42:11 PM] [Config] Running in Service Mode
[6/3/2021, 4:42:11 PM] [Nest-cam] Initializing Nest-cam platform...
[6/3/2021, 4:42:11 PM] [Nest-cam] Using motionDetection from config: true
[6/3/2021, 4:42:11 PM] [Nest-cam] Defaulting doorbellAlerts to true
[6/3/2021, 4:42:11 PM] [Nest-cam] Defaulting doorbellSwitch to true
[6/3/2021, 4:42:11 PM] [Nest-cam] Using streamingSwitch from config: true
[6/3/2021, 4:42:11 PM] [Nest-cam] Defaulting chimeSwitch to true
[6/3/2021, 4:42:11 PM] [Nest-cam] Using announcementsSwitch from config: true
[6/3/2021, 4:42:11 PM] [Nest-cam] Using audioSwitch from config: true
[6/3/2021, 4:42:11 PM] [Nest-cam] Defaulting structures to []
[6/3/2021, 4:42:11 PM] Ignoring config for the platform "SensiboAC" in your config.json as the plugin "homebridge-sensibo-ac" has been disabled.
[6/3/2021, 4:42:11 PM] [home] Initializing GogoGate2 platform...
[6/3/2021, 4:42:11 PM] [WizSmarthome] Initializing WizSmarthome platform...
[6/3/2021, 4:42:11 PM] [Nest-cam] Configuring accessory Back
[6/3/2021, 4:42:11 PM] [Nest-cam] Using importantOnly from config: true
[6/3/2021, 4:42:11 PM] [Nest-cam] Creating microphone for Back.
[6/3/2021, 4:42:11 PM] [Nest-cam] Creating switch for Back Streaming.
[6/3/2021, 4:42:11 PM] [Nest-cam] Creating switch for Back Audio.
[6/3/2021, 4:42:11 PM] [Nest-cam] Configuring accessory Front
[6/3/2021, 4:42:11 PM] [Nest-cam] Using importantOnly from config: true
[6/3/2021, 4:42:11 PM] [Nest-cam] Creating microphone for Front.
[6/3/2021, 4:42:11 PM] [Nest-cam] Creating switch for Front Streaming.
[6/3/2021, 4:42:11 PM] [Nest-cam] Creating switch for Front Audio.
[6/3/2021, 4:42:11 PM] [Nest-cam] Authenticating via Google refresh token.
[6/3/2021, 4:42:11 PM] [home] DidFinishLaunching
[6/3/2021, 4:42:11 PM] [home] INFO - LOGIN - trying to log
[6/3/2021, 4:42:11 PM] [WizSmarthome] Executed didFinishLaunching callback
[6/3/2021, 4:42:11 PM] [WizSmarthome] [Socket] Setting up socket on 192.168.1.2:38900
Preparing Advertiser for 'Homebridge CA82 2FEC' using bonjour-hap backend!
Setup Payload:
X-HM://0023ISYWYDVM5

**Comment by stevie-po** [comment]
plugin config:
{
    "name": "home",
    "gogogateIP": "192.168.1.6",
    "username": "xxx",
    "password": "xxx",
    "refreshTimer": 120,
    "maxWaitTimeForOperation": 35,
    "refreshTimerDuringOperation": 10,
    "platform": "GogoGate2"
}
