### ISSUE TITLE
Homebridge Crashes with latest version 0.0.4

### ISSUE THREAD

**Issue by designzguy** [nicoduj/homebridge-gogogate2#6]
When attempting to open/close garage door with latest version 0.0.4 Homebridge crashes.

Homebridge log with crash attached shown below:

C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:459
        that.debug('activateDoor - Command sent to ' + controlService.subtype);
             ^
TypeError: that.debug is not a function
    at Request.optionalCallback [as _callback] (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\index.js:459:14)
    at Request.self.callback (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\homebridge\AppData\Roaming\npm\node_modules\homebridge-gogogate2\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by nicoduj** [comment]
Hi,

Noted sorry for that :( will fix tomorrow evening !

**Comment by nicoduj** [comment]
The fix is in the repository you can update index.js if you want i will publish to npm asap tomorrow evening . Sorry again for this mistake.

**Comment by designzguy** [comment]
I've installed the latest 0.0.5 version and can confirm it is working again, thank you for the quick fix.

**Comment by nicoduj** [comment]
Fixed in 
https://github.com/nicoduj/homebridge-gogogate2/releases/tag/0.0.5
